### ISSUE TITLE
Add schema definition for files in input_data task

### ISSUE THREAD

**Issue by jacklchang** [morrisanimalfoundation/raritan#13]
In the input_data task there are cases where a file is optional and so if it does not exist in the folder, the flow will continue. 

But, it will later fail because the code will reference that table. So this issue should create an empty dataframe for missing optional files and take in column names as parameters.

**Comment by jacklchang** [comment]
In `decorators.py`:
```
  if not os.path.exists(group + '/' + name):
      # It is not optional
      if not inner_optional_flag:
          raise FileNotFoundError(f"Non-Optional file missing: {name}")
      else:
          logger.info(f"Optional file missing: {name}")
          continue  # Skip processing if file is optional
```

So we are in the `else` case when the optional file is missing. This means that the file is not critical to the data but we need some placeholder in order for the flow to properly execute. 

Right now we are handling it in the ETL like:

```
    if os.path.exists(settings.dictionary_dir + '/poison_substance_dictionary.csv'):
        previous_dictionary = pd.read_csv(settings.dictionary_dir + "/poison_substance_dictionary.csv", header=0)
    else:
        previous_dictionary = pd.DataFrame(
            columns=['input_substance', 'output_substance', 'drop', 'resolved'])
```

There are a few approaches I am thinking of:

1. Passing in the column list when we are doing input_data and it will create it in the else case.
2. Create an input_dictionary handler (since in the ETL dictionaries are being imported separately from the data)
3. Default create all dictionaries based off a dictionary schema file and set_context on top of it, if the file does exist.

**Comment by lkacenja** [comment]
I like option #1, but I'd argue it would be good to pass the entire schema with dtypes through. 
```
@input_data(parallel=False)
def get_data() -> dict:
    """
    Gets our flow data and stores it inside the context object.
    """
    return {
        settings.dictionary_dir: {
            'labs_dictionary': {
                'optional': True,
                'file': 'multi_column_dictionary_labs.csv',
                'default': {
                  'input': 'string',
                  'output': 'string',
                 'resolved': 'Int64',
                },
            }
        }
    }
```

Another separate option would be to have the flow provide a default dictionary as a df. We could just pass it around and Raritan would still not need to know what is in default.

```
default_dictionary = pd.DataFrame(columns=['input', 'output'])

@input_data(parallel=False)
def get_data() -> dict:
    """
    Gets our flow data and stores it inside the context object.
    """
    return {
        settings.dictionary_dir: {
            'labs_dictionary': {
                'optional': True,
                'file': 'multi_column_dictionary_labs.csv',
                'default': default_dictionary,
            }
        }
    }
```

**Comment by jacklchang** [comment]
I think option 1 could make the return function very long. E.g. medication topic has 5 dictionaries. 

The second option is more like what we did for the filtering so I like that! I'll try that. Kind of like the 3rd suggestion I had - making a dictionary schema file that defines:
```
dictionary_name: {
                  'input': 'string',
                  'output': 'string',
                  'drop': 'Int64',
                 'resolved': 'Int64',
}
```

This is better than the current ETL setup anyways because we aren't currently defining the data types.
