### ISSUE TITLE
Further improve stack traces

### ISSUE THREAD

**Issue by lkacenja** [morrisanimalfoundation/raritan#8]
Our efforts to improve stack traces somewhat backfired. Right now we see a shorter stack trace, but often the frame with the actual offending code is omitted. This makes debugging a little tricky.

Our original goal was to show less irrelevant information and more good stuff. We should stick to that ideal and try again. I propose three phases to this effort.

1. Research how we could improve stack traces.
2. Implement findings.
3. Allow stack trace information to be alterable by child repos.

**Comment by jack-maf** [comment]
Logging Modules
[Loguru](https://loguru.readthedocs.io/en/stable/) 
Textualize/[rich](https://rich.readthedocs.io/en/latest/traceback.html) 
[pdb](https://docs.python.org/3/library/pdb.html) 
[traceback](https://docs.python.org/3/library/traceback.html#module-traceback)

**Comment by lkacenja** [comment]
I think exploring some logging packages seems like a great idea. If we want to keep rich, you could explore more fine grained control of the number of stack trace "frames" that are shown. I believe you can also to some extent see the code related to the various frames. I wondered if it would be possible to find where our decorator function are in the stack trace, and use them as an anchor to trim from. That might be kind of tricky.
